In [31]:
import pandas as pd

apartment_data = pd.read_excel('data/apartment_data.xlsx')
print(apartment_data.dtypes)
print(apartment_data.info())
apartment_data.head()

ApartmentID            int64
BasePricePerNight    float64
NumberOfBedrooms       int64
AddressID              int64
UserID                 int64
Country                  str
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ApartmentID        20 non-null     int64
 1   BasePricePerNight  20 non-null     float64
 2   NumberOfBedrooms   20 non-null     int64
 3   AddressID          20 non-null     int64
 4   UserID             20 non-null     int64
 5   Country            20 non-null     str
dtypes: float64(1), int64(4), str(1)
memory usage: 1.1 KB
None

   ApartmentID  BasePricePerNight  NumberOfBedrooms  AddressID  UserID Country
0            1              120.0                 2          3       3     NLD
1            2               85.0                 1          3       3     NLD
2            3              250.0                 3         30       3     DEU
3            4               95.0                 1         26       6     AUT
4            5              150.0                 2         26       6     AUT

In [30]:
cohosts = pd.read_csv('data/cohost_apartment.csv')
print(cohosts.dtypes)
cohosts.head()

ApartmentID    int64
CoHostID       int64
dtype: object

   ApartmentID  CoHostID
0            1        14
1            2        14
2            4        11
3            5        11
4            6        11

In [5]:
# user_df = pd.read_csv('data/user_addresses.csv')
# print(user_df.dtypes)
# user_df.head()

In [6]:
bookings = pd.read_excel('data/bookings.xlsx')
print(bookings.dtypes)
bookings.head()

ApartmentID            int64
BasePricePerNight    float64
NumberOfBedrooms       int64
AddressID              int64
UserID                 int64
Country                  str
dtype: object

   ApartmentID  BasePricePerNight  NumberOfBedrooms  AddressID  UserID Country
0            1              120.0                 2          3       3     NLD
1            2               85.0                 1          3       3     NLD
2            3              250.0                 3         30       3     DEU
3            4               95.0                 1         26       6     AUT
4            5              150.0                 2         26       6     AUT

In [9]:
apartment_ams = pd.read_excel(r'data\apartment_amenities.xlsx')
print(apartment_ams.dtypes)
apartment_ams.head()

ApartmentID    int64
Amenity          str
dtype: object

   ApartmentID        Amenity
0            1           WiFi
1            1  Swimming Pool
2            1          Sauna
3            1       Smart TV
4            2           WiFi

In [10]:
booking_full = pd.read_excel(r'data\booking_full.xlsx')
print(booking_full.dtypes)
booking_full.head()

BookingID             int64
UserID                int64
NumberOfGuests        int64
TotalNights           int64
PricePerNight       float64
ApartmentID           int64
NumberOfBedrooms      int64
Country                 str
HostUserID            int64
dtype: object

,BookingID,UserID,NumberOfGuests,TotalNights,PricePerNight,ApartmentID,NumberOfBedrooms,Country,HostUserID
0,1,10,4,9,140.0,12,2,FRA,15
1,2,14,5,9,220.0,17,3,DEU,18
2,3,13,1,10,70.0,15,1,DEU,15
3,4,19,1,3,85.0,2,1,NLD,3
4,5,18,2,4,400.0,6,4,AUT,6

In [11]:
feetypes = pd.read_excel('data/feetypes.xlsx')
print(feetypes.dtypes)
feetypes.head()

FeeTypeID    int64
Type           str
Category       str
dtype: object

   FeeTypeID            Type Category
0          1        Cleaning     Host
1          2            Pets     Host
2          3     Extra Guest     Host
3          4  Late Check-out     Host
4          5  Early Check-in     Host

In [21]:
feetypes.iloc[feetypes['Type'] == 'Cleaning']['FeeTypeID']

0    1
Name: FeeTypeID, dtype: int64

In [26]:
feetypes['FeeTypeID']

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
Name: FeeTypeID, dtype: int64