In [10]:
import pandas as pd

apartment_data = pd.read_csv('data/apartment_data.csv')
print(apartment_data.dtypes)
print(apartment_data.info())
apartment_data

ApartmentID             int64
 "BasePricePerNight"      str
 "NumberOfBedrooms"       str
 "AddressID"              str
 "UserID"                 str
 "Country"                str
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ApartmentID           20 non-null     int64
 1    "BasePricePerNight"  20 non-null     str
 2    "NumberOfBedrooms"   20 non-null     str
 3    "AddressID"          20 non-null     str
 4    "UserID"             20 non-null     str
 5    "Country"            20 non-null     str
dtypes: int64(1), str(5)
memory usage: 1.1 KB
None

,ApartmentID,"""BasePricePerNight""","""NumberOfBedrooms""","""AddressID""","""UserID""","""Country"""
0,1,"""120.00""","""2""","""3""","""3""","""NLD"""
1,2,"""85.00""","""1""","""3""","""3""","""NLD"""
2,3,"""250.00""","""3""","""30""","""3""","""DEU"""
3,4,"""95.00""","""1""","""26""","""6""","""AUT"""
4,5,"""150.00""","""2""","""26""","""6""","""AUT"""
5,6,"""400.00""","""4""","""26""","""6""","""AUT"""
6,7,"""75.00""","""1""","""28""","""6""","""AUT"""
7,8,"""110.00""","""2""","""28""","""6""","""AUT"""
8,9,"""90.00""","""1""","""9""","""9""","""AUT"""
9,10,"""600.00""","""5""","""22""","""13""","""FRA"""
10,11,"""300.00""","""3""","""29""","""13""","""FRA"""
11,12,"""140.00""","""2""","""29""","""15""","""FRA"""
12,13,"""180.00""","""2""","""21""","""15""","""DEU"""
13,14,"""65.00""","""1""","""23""","""15""","""DEU"""
14,15,"""70.00""","""1""","""24""","""15""","""DEU"""
15,16,"""130.00""","""2""","""27""","""15""","""DEU"""
16,17,"""220.00""","""3""","""25""","""18""","""DEU"""
17,18,"""80.00""","""1""","""30""","""18""","""DEU"""
18,19,"""500.00""","""4""","""12""","""18""","""DEU"""
19,20,"""160.00""","""2""","""7""","""18""","""DEU"""

In [11]:
cohosts = pd.read_csv('data/cohost_apartment.csv')
print(cohosts.dtypes)
cohosts.head()

ApartmentID    int64
CoHostID       int64
dtype: object

   ApartmentID  CoHostID
0            1        14
1            2        14
2            4        11
3            5        11
4            6        11

In [12]:
user_df = pd.read_csv('data/user_addresses.csv')
print(user_df.dtypes)
user_df.head()

UserID       int64
AddressID    int64
dtype: object

   UserID  AddressID
0       1          1
1       2          2
2       3          3
3       4          4
4       5          5

In [ ]:
bookings = pd.read_excel('data/bookings.xlsx')
print(bookings.dtypes)
bookings.head()

ApartmentID            int64
BasePricePerNight    float64
NumberOfBedrooms       int64
AddressID              int64
UserID                 int64
Country                  str
dtype: object

   ApartmentID  BasePricePerNight  NumberOfBedrooms  AddressID  UserID Country
0            1              120.0                 2          3       3     NLD
1            2               85.0                 1          3       3     NLD
2            3              250.0                 3         30       3     DEU
3            4               95.0                 1         26       6     AUT
4            5              150.0                 2         26       6     AUT