In [1]:
import pandas as pd
import numpy as np
from datetime import date, datetime, timedelta


file = "data/payments.txt"

headers = [
    "receipt",
    "sub_total",
    "service_fee",
    "total_tax",
    "total_amount",
    "booking_id",
    "method",
    "address",
    "Nothing",
]

raw_payments = pd.read_csv(file, header=None, names=headers, index_col=None)

display(raw_payments.head())
print(raw_payments.columns)

,receipt,sub_total,service_fee,total_tax,total_amount,booking_id,method,address,Nothing
0,('2026-03-27 23:05:15',1440.0,53.07,302,1795.07,1,1,11),
1,('2026-05-05 05:20:54',260.0,61.40,10,331.40,2,10,19),
2,('2026-03-15 03:21:44',340.0,36.42,24,400.42,3,5,29),
3,('2026-07-13 10:57:01',2100.0,24.89,147,2271.89,4,2,27),
4,('2026-02-14 02:41:20',720.0,158.70,27,905.70,5,3,26),

Index(['receipt', 'sub_total', 'service_fee', 'total_tax', 'total_amount',
       'booking_id', 'method', 'address', 'Nothing'],
      dtype='str')

In [2]:
cols = [
    "receipt",
    "sub_total",
    "service_fee",
    "total_tax",
    "total_amount",
    "booking_id",
    "method",
    "address",
]

payments = raw_payments[cols]

payments["receipt"] = payments["receipt"].str.strip("(")
payments["receipt"] = pd.to_datetime(payments["receipt"])
payments["address"] = payments["address"].str.strip(") ").astype(int)

display(payments.head(3))
print(payments.dtypes)

,receipt,sub_total,service_fee,total_tax,total_amount,booking_id,method,address
0,2026-03-27 23:05:15,1440.0,53.07,302,1795.07,1,1,11
1,2026-05-05 05:20:54,260.0,61.40,10,331.40,2,10,19
2,2026-03-15 03:21:44,340.0,36.42,24,400.42,3,5,29

receipt         datetime64[us]
sub_total              float64
service_fee            float64
total_tax                int64
total_amount           float64
booking_id               int64
method                   int64
address                  int64
dtype: object

In [3]:
new_date = payments["receipt"][0] + timedelta(hours=24)

print(new_date)

2026-03-28 23:05:15

In [ ]:
file = "data/host_payments.txt"

host_headers = [
    "pay_date",
    "gross",
    "commission",
    "host_fees",
    "net",
    "share",
    "paid_to",
    "payment_id",
    "payee_id",
    'Nothing'
]

raw_hosts = pd.read_csv(file, header=None, names=host_headers, index_col=None)

host_cols = [
    "pay_date",
    "gross",
    "commission",
    "host_fees",
    "net",
    "share",
    "paid_to",
    "payment_id",
    "payee_id",
]

hosts = raw_hosts[host_cols]

hosts['pay_date'] = hosts['pay_date'].str.strip('(')
hosts['pay_date'] = pd.to_datetime(hosts['pay_date'])
hosts['payee_id'] = hosts["payee_id"].str.strip(')')

hosts.head()

,pay_date,gross,commission,host_fees,net,share,paid_to,payment_id,payee_id
0,2026-01-04 04:09:54,2669.43,75.08,91.58,2594.35,0.96,'Host,1,1
1,2026-03-04 20:27:12,948.28,26.00,55.48,922.28,1.00,'Host,2,7
2,2026-06-09 13:58:59,1842.41,52.41,43.03,1790.00,1.00,'Host,3,7
3,2026-01-18 22:46:16,993.27,28.36,19.53,964.91,0.43,'CoHost,4,7
4,2026-01-10 21:40:59,1193.81,34.05,24.83,1159.76,1.00,'Host,5,12

In [26]:
bookings = pd.read_csv(r"data\booking_data.csv")
bookings["check_in"] = pd.to_datetime(bookings["check_in"])
bookings["check_out"] = pd.to_datetime(bookings["check_out"])
bookings["booking_date"] = pd.to_datetime(bookings["booking_date"])

print(bookings.dtypes)
print(bookings.head())

booking_date    datetime64[us]
check_in        datetime64[us]
check_out       datetime64[us]
num_guests               int64
price                  float64
total_nights             int64
user_id                  int64
dtype: object
         booking_date   check_in  check_out  num_guests  price  total_nights  \
0 2026-01-03 04:09:54 2026-03-17 2026-03-26           4  220.0             9
1 2026-03-03 20:27:12 2026-11-23 2026-12-02           1   80.0             9
2 2026-06-08 13:58:59 2026-06-21 2026-06-28           2  220.0             7
3 2026-01-17 22:46:16 2026-06-28 2026-07-10           5   75.0            12
4 2026-01-09 21:40:59 2026-03-10 2026-03-14           2  220.0             4

   user_id
0        7
1        6
2        3
3       18
4       15