In [2]:
from faker import Faker
import numpy as np
import pandas as pd
import random
from unidecode import unidecode
from datetime import date, timedelta

locales = ["de_DE", "de_AT", "de_CH"]

fake = Faker(locale=locales)

print(fake.date_time_this_year())

2026-04-18 07:09:00

In [3]:
file = r"G:\My Drive\Coding\SQL_dummy_data\data\booking_data.txt"

headers = [
    "booking_date",
    "check_in",
    "check_out",
    "num_guests",
    "price",
    "total_nights",
    "booking_type",
    "user_id",
    "apartment",
    "Nothing",
]
bookings = pd.read_csv(file, header=None, names=headers, index_col=None)
bookings["check_in"] = pd.to_datetime(bookings["check_in"])
bookings["check_out"] = pd.to_datetime(bookings["check_out"])
bookings["apartment"] = bookings["apartment"].str.strip(")").astype(int)

cols = [
    "check_in",
    "check_out",
    "num_guests",
    "price",
    "total_nights",
    "booking_type",
    "user_id",
    "apartment",
]

needed_bookings = bookings[cols]

print(needed_bookings.info())

needed_bookings.head()
# needed_bookings.to_csv(r"G:\My Drive\Coding\SQL_dummy_data\data\booking_data.csv")

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   check_in      40 non-null     datetime64[us]
 1   check_out     40 non-null     datetime64[us]
 2   num_guests    40 non-null     int64
 3   price         40 non-null     float64
 4   total_nights  40 non-null     int64
 5   booking_type  40 non-null     int64
 6   user_id       40 non-null     int64
 7   apartment     40 non-null     int64
dtypes: datetime64[us](2), float64(1), int64(5)
memory usage: 2.6 KB
None

,check_in,check_out,num_guests,price,total_nights,booking_type,user_id,apartment
0,2026-09-09,2026-09-15,2,75.0,6,6,15,7
1,2026-02-10,2026-02-13,5,70.0,3,3,2,14
2,2026-09-05,2026-09-09,2,75.0,4,3,20,7
3,2026-07-18,2026-07-30,1,95.0,12,10,11,4
4,2026-04-13,2026-04-25,5,70.0,12,4,9,14

In [8]:
def generate_payment(row: int, df: pd.DataFrame = needed_bookings) -> tuple | None:

    if df["check_in"][row] > pd.to_datetime(date.today()):
        return None

    receipt = str(fake.date_time_this_year(before_now=True, after_now=False))

    sub_total = df["price"][row] * df["total_nights"][row]
    service_fee = round(200 * random.random(), 2)
    total_tax = round(50 * random.random(), 2)
    total_amount = round(sub_total + service_fee + total_tax, 2)
    booking_id = row
    method = random.randint(0, 10)
    address = random.randint(1, 30)

    return (
        receipt,
        float(sub_total),
        service_fee,
        total_tax,
        float(total_amount),
        booking_id,
        method,
        address,
    )


for i in range(len(needed_bookings)):
    payment = generate_payment(i)
    if payment is None:
        continue
    else:
        print(payment)

('2026-03-18 01:36:33', 210.0, 47.69, 39.85, 297.54, 1, 7, 20)
('2026-02-04 03:40:59', 1140.0, 14.52, 31.59, 1186.11, 3, 5, 21)
('2026-01-17 12:22:57', 840.0, 109.12, 18.86, 967.98, 4, 7, 26)
('2026-05-13 20:48:38', 595.0, 107.87, 25.11, 727.98, 5, 9, 3)
('2026-07-21 09:07:50', 1980.0, 93.47, 9.42, 2082.89, 6, 8, 20)
('2026-04-24 10:45:45', 3000.0, 89.3, 26.56, 3115.86, 7, 9, 14)
('2026-04-11 22:03:16', 220.0, 122.36, 49.72, 392.08, 8, 8, 1)
('2026-08-01 06:33:41', 1440.0, 160.25, 15.43, 1615.68, 9, 5, 11)
('2026-05-30 06:42:34', 1650.0, 59.38, 42.02, 1751.4, 10, 1, 18)
('2026-07-24 06:42:57', 960.0, 39.85, 1.71, 1001.56, 13, 2, 16)
('2026-04-23 00:03:26', 1540.0, 63.34, 11.02, 1614.36, 14, 5, 16)
('2026-02-07 12:11:36', 95.0, 89.2, 36.15, 220.35, 15, 1, 6)
('2026-05-05 17:56:42', 300.0, 92.9, 31.31, 424.21, 16, 2, 19)
('2026-07-21 12:32:08', 330.0, 192.92, 12.27, 535.19, 17, 1, 11)
('2026-01-21 08:51:36', 975.0, 52.22, 16.93, 1044.15, 18, 3, 8)
('2026-01-19 18:10:53', 65.0, 86.82, 45.3, 197.12, 19, 10, 5)
('2026-03-11 13:42:09', 525.0, 67.96, 24.02, 616.98, 21, 2, 1)
('2026-03-12 08:45:04', 300.0, 33.05, 45.23, 378.28, 27, 2, 24)
('2026-04-05 07:02:55', 520.0, 199.75, 30.53, 750.28, 28, 6, 1)
('2026-02-09 19:45:32', 350.0, 45.75, 43.17, 438.92, 29, 0, 24)
('2026-07-31 15:57:17', 640.0, 155.04, 15.75, 810.79, 31, 10, 8)
('2026-03-30 17:22:22', 4500.0, 197.22, 16.01, 4713.23, 32, 5, 14)
('2026-04-03 14:10:39', 700.0, 139.28, 35.48, 874.76, 36, 1, 16)
('2026-08-05 07:34:48', 1020.0, 36.89, 2.16, 1059.05, 37, 10, 30)
('2026-03-19 19:41:22', 720.0, 83.56, 49.2, 852.76, 38, 9, 21)
('2026-03-20 23:08:49', 4000.0, 184.28, 20.67, 4204.95, 39, 0, 10)

In [5]:
for i in range(len(needed_bookings)):
    payment = generate_payment(i)
    if payment is None:
        continue
    else:
        print(payment)

('2026-01-15 23:30:27', 210.0, 147.89, 28.39, 386.28, 1, 7, 4)
('2026-04-04 12:23:54', 1140.0, 34.5, 25.57, 1200.07, 3, 7, 30)
('2026-05-16 17:31:35', 840.0, 104.32, 21.95, 966.27, 4, 10, 1)
('2026-07-25 20:01:34', 595.0, 78.88, 10.7, 684.58, 5, 0, 20)
('2026-05-18 15:03:01', 1980.0, 190.91, 37.06, 2207.97, 6, 8, 30)
('2026-02-13 01:05:42', 3000.0, 112.58, 31.14, 3143.72, 7, 10, 29)
('2026-05-18 16:25:11', 220.0, 150.68, 9.0, 379.68, 8, 5, 24)
('2026-01-14 11:54:56', 1440.0, 109.66, 37.46, 1587.12, 9, 8, 9)
('2026-04-09 20:37:42', 1650.0, 159.91, 19.87, 1829.78, 10, 0, 21)
('2026-07-25 22:36:36', 960.0, 146.81, 46.42, 1153.23, 13, 0, 7)
('2026-06-11 18:02:30', 1540.0, 36.4, 5.88, 1582.28, 14, 9, 9)
('2026-03-23 16:41:28', 95.0, 52.01, 38.9, 185.91, 15, 10, 22)
('2026-05-13 13:30:47', 300.0, 15.49, 23.48, 338.97, 16, 7, 1)
('2026-05-01 17:01:02', 330.0, 55.86, 0.78, 386.64, 17, 7, 21)
('2026-02-03 05:01:44', 975.0, 124.99, 14.93, 1114.92, 18, 5, 2)
('2026-02-16 21:14:56', 65.0, 155.34, 31.05, 251.39, 19, 5, 17)
('2026-05-08 04:59:24', 525.0, 0.73, 18.27, 544.0, 21, 1, 25)
('2026-06-03 20:11:05', 300.0, 149.66, 24.4, 474.06, 27, 2, 3)
('2026-01-07 06:08:26', 520.0, 195.03, 39.27, 754.3, 28, 2, 26)
('2026-03-03 02:52:32', 350.0, 99.16, 37.21, 486.37, 29, 7, 24)
('2026-03-09 13:03:49', 640.0, 193.07, 21.71, 854.78, 31, 4, 10)
('2026-08-09 08:08:43', 4500.0, 121.12, 8.31, 4629.43, 32, 1, 15)
('2026-03-07 15:28:48', 700.0, 162.1, 18.58, 880.68, 36, 5, 27)
('2026-04-15 02:02:44', 1020.0, 40.53, 20.99, 1081.52, 37, 2, 28)
('2026-04-15 02:09:57', 720.0, 23.67, 41.53, 785.2, 38, 4, 19)
('2026-02-07 17:59:13', 4000.0, 38.87, 39.92, 4078.79, 39, 6, 2)

In [ ]:
fake_ger = Faker("de_DE")

# specifying first and last name
first_name = fake_ger.first_name()
last_name = fake_ger.last_name()

# combining first and last name
full_name = f"{first_name} {last_name}"
print(full_name)

# creating an email based on the name
first_name_cleaned = unidecode(first_name.lower())
last_name_cleaned = unidecode(last_name.lower())
email = f"{first_name_cleaned}.{last_name_cleaned}@{fake.free_email_domain()}"
print(email)

Marie-Louise Faust
marie-louise.faust@gmail.com

In [ ]:
def generate_personal_data(locale: str):
    fake = Faker(locale)

    first_name = fake.first_name()
    last_name = fake.last_name()
    full_name = f"{first_name} {last_name}"

    email_first = unidecode(first_name.lower()).replace(" ", "")
    email_last = unidecode(last_name.lower()).replace(" ", "")

    email = f"{email_first}.{email_last}@{fake.free_email_domain()}"

    address = fake.address().replace("\n", ", ")

    return full_name, email, address


locales = [
    "de_DE",
    "de_AT",
    "de_CH",
    "it_IT",
    "fr_FR",
    "en_GB",
    "da_DK",
    "es_ES",
    "nl_NL",
    "sv_SE",
    "no_NO",
]

people_data = []

for person in range(21):
    locale = random.choice(locales)
    people_data.append(generate_personal_data(locale))


df = pd.DataFrame(people_data, columns=("name", "email", "address"))

df

,name,email,address
0,Karl-August Seifert,karl-august.seifert@gmail.com,"Adelheid-Krebs-Straße 79-10, 65631 Steinfurt"
1,Else Danielsen,else.danielsen@yahoo.com,"Paulsenberget 99A, 3111 Holm"
2,Rufina Ordóñez,rufina.ordonez@yahoo.com,"Urbanización María Manuela Llano 335, Granada,..."
3,Baldassare Ferrara,baldassare.ferrara@hotmail.it,"Canale Fornaciari, 13 Appartamento 7, 00019, P..."
4,Mihaela Zingg,mihaela.zingg@yahoo.com,"Martinstrasse 51, 5010 Bülach"
5,Christian Tveit,christian.tveit@yahoo.com,"Hellandfaret 99, 1630 Ellingsen"
6,Bryan Ward,bryan.ward@yahoo.co.uk,"842 Potter Lake, West Wendy, KT0V 5BP"
7,Isak Bergström,isak.bergstrom@telia.com,"Kyrkovägen 40, 82264 Lund"
8,Olivier Thomas,olivier.thomas@hotmail.com,"Collinring 847, 6679NB, Puth"
9,Patrick Ackerl,patrick.ackerl@gmail.com,"Wenzlweg 25, 8259 Melk"
10,Anne Morris,anne.morris@outlook.com,"598 Rahman Mountains, Christianstad, KA2R 6RH"
11,Dina Lind,dina.lind@hotmail.com,"Gammel Køge Landevej 2, 3164 Løkken"
12,Johan Gashi,johan.gashi@spray.se,"Strandstigen 4, 87467 Borlänge"
13,Jonas van den Nuwenhuijzen,jonas.vandennuwenhuijzen@hotmail.com,"Esméering 2, 9959ZJ, Posterholt"
14,Calogero Iannuzzi,calogero.iannuzzi@fastwebnet.it,"Strada Iadanza, 64 Appartamento 80, 73055, Rac..."
15,Jens Blees,jens.blees@yahoo.com,"Guusdreef 037, 3139 DG, Piershil"
16,Geir Abrahamsen,geir.abrahamsen@hotmail.com,"Rønningengen 44, 4663 Johanborg"
17,Edith Brandt,edith.brandt@gmail.com,"Dunkerquegade 14, 7008 Hvalsø"
18,Serafina Luna,serafina.luna@tele2.it,"Incrocio Lanfranchi, 5, 20124, Milano (MI)"
19,Daniela Hedberg,daniela.hedberg@swipnet.se,"Skolvägen 03, 60013 Norrköping"
20,Ayse Hirt,ayse.hirt@hotmail.com,"Mayerstrasse 55, 7877 Thalwil"

In [ ]:
addresses = []

for i in range(11):
    addresses.append(fake.address())

print(addresses)

['Albrechtstrasse 49\n7989 Siders', 'Hattingerstraße 855\n5741 Klagenfurt', 'Krausallee 38/37\n88282 Heinsberg', 'Kocherstr. 9/0\n8849 Gallneukirchen', 'Sylvie-Gertz-Platz 57/12\n64356 Olpe', 'Prantlgasse 9/2\n7887 Hartberg', 'Ottstrasse 50\n2859 Luzern', 'Mielcarekgasse 0\n69312 Kelheim', 'Anna-Kuhl-Gasse 37\n49658 Gelnhausen', 'Martinstrasse 55\n6372 Uster', 'Meixnerstr. 26\n3297 Hainburg an der Donau']

In [ ]:
check_in = fake.date_this_year(True, True)

min_stay = check_in + timedelta(days=1)
max_stay = check_in + timedelta(days=14)

check_out = fake.date_between_dates(date_start=min_stay, date_end=max_stay)

print(check_in)
print(check_out)

2026-11-28
2026-12-10