In [1]:
from faker import Faker
import numpy as np
import pandas as pd
import random
from unidecode import unidecode
from datetime import date, timedelta

locales = ["de_DE", "de_AT", "de_CH"]

fake = Faker(locale=locales)

print(fake.date_time_this_year())

2026-07-31 02:04:48

In [2]:
file = r"G:\My Drive\Coding\SQL_dummy_data\data\booking_data.txt"

headers = [
    "booking_date",
    "check_in",
    "check_out",
    "num_guests",
    "price",
    "total_nights",
    "booking_type",
    "user_id",
    "apartment",
    "Nothing",
]
bookings = pd.read_csv(file, header=None, names=headers, index_col=None)
bookings["check_in"] = pd.to_datetime(bookings["check_in"])
bookings["check_out"] = pd.to_datetime(bookings["check_out"])
bookings["apartment"] = bookings["apartment"].str.strip(")").astype(int)

cols = [
    "check_in",
    "check_out",
    "num_guests",
    "price",
    "total_nights",
    "booking_type",
    "user_id",
    "apartment",
]

needed_bookings = bookings[cols]

print(needed_bookings.info())

needed_bookings.head()
# needed_bookings.to_csv(r"G:\My Drive\Coding\SQL_dummy_data\data\booking_data.csv")

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   check_in      40 non-null     datetime64[us]
 1   check_out     40 non-null     datetime64[us]
 2   num_guests    40 non-null     int64
 3   price         40 non-null     float64
 4   total_nights  40 non-null     int64
 5   booking_type  40 non-null     int64
 6   user_id       40 non-null     int64
 7   apartment     40 non-null     int64
dtypes: datetime64[us](2), float64(1), int64(5)
memory usage: 2.6 KB
None

,check_in,check_out,num_guests,price,total_nights,booking_type,user_id,apartment
0,2026-08-29,2026-09-03,5,95.0,5,7,11,4
1,2026-07-19,2026-07-24,1,75.0,5,5,11,7
2,2026-06-07,2026-06-17,3,85.0,10,2,7,2
3,2026-04-30,2026-05-03,5,110.0,3,1,15,8
4,2026-11-10,2026-11-15,3,80.0,5,9,14,18

In [11]:
def generate_payment(row: int, df: pd.DataFrame = needed_bookings) -> tuple | None:

    if  df["check_in"][row] >  pd.to_datetime(date.today()):
        return None

    receipt = str(fake.date_time_this_year(before_now=True, after_now=False))

    sub_total = df["price"][row] * df["total_nights"][row]
    service_fee = round(200 * random.random(), 2)
    total_tax = round(50 * random.random(), 2)
    total_amount = round(sub_total + service_fee + total_tax, 2)
    booking_id = row
    method = random.randint(0,10)
    address = random.randint(1, 30)

    return (
        receipt,
        float(sub_total),
        service_fee,
        total_tax,
        float(total_amount),
        booking_id,
        method,
        address,
    )

In [14]:
for i in range(len(needed_bookings)):
    payment = generate_payment(i)    
    if payment is None:
        continue
    else:
        print(payment)

('2026-05-03 16:50:28', 375.0, 8.75, 41.94, 425.69, 1, 3, 28)
('2026-05-22 06:08:19', 850.0, 142.36, 1.62, 993.98, 2, 1, 5)
('2026-04-04 02:17:48', 330.0, 128.75, 20.66, 479.41, 3, 8, 17)
('2026-07-14 03:43:31', 630.0, 174.51, 46.67, 851.18, 7, 9, 14)
('2026-07-13 22:47:48', 1020.0, 128.59, 15.29, 1163.88, 9, 10, 23)
('2026-05-19 06:52:32', 80.0, 56.4, 13.65, 150.05, 11, 9, 30)
('2026-08-09 07:38:42', 450.0, 17.32, 11.5, 478.82, 12, 5, 23)
('2026-02-28 02:11:11', 570.0, 14.76, 12.83, 597.59, 14, 5, 10)
('2026-04-19 11:26:22', 400.0, 34.2, 46.95, 481.15, 15, 3, 15)
('2026-02-13 23:19:45', 450.0, 117.77, 35.79, 603.56, 16, 9, 7)
('2026-02-27 10:39:45', 1800.0, 150.65, 40.46, 1991.11, 17, 8, 18)
('2026-01-24 14:45:02', 220.0, 122.15, 3.03, 345.18, 24, 1, 12)
('2026-03-06 23:47:22', 2080.0, 10.41, 3.57, 2093.98, 25, 10, 11)
('2026-02-14 20:56:39', 3000.0, 168.36, 31.43, 3199.79, 26, 4, 12)
('2026-03-16 17:53:03', 840.0, 57.84, 11.44, 909.28, 27, 9, 10)
('2026-02-28 15:59:19', 85.0, 171.93, 45.66, 302.59, 28, 10, 11)
('2026-06-20 05:46:47', 5200.0, 35.4, 16.94, 5252.34, 29, 0, 10)
('2026-01-13 01:38:58', 1400.0, 173.25, 19.92, 1593.17, 33, 3, 11)
('2026-05-25 13:33:56', 400.0, 139.1, 17.22, 556.32, 35, 3, 7)
('2026-02-09 22:26:26', 990.0, 56.6, 11.27, 1057.87, 37, 0, 4)
('2026-05-05 19:57:16', 630.0, 179.83, 47.5, 857.33, 38, 9, 8)

In [2]:
fake_ger = Faker("de_DE")

# specifying first and last name
first_name = fake_ger.first_name()
last_name = fake_ger.last_name()

# combining first and last name
full_name = f"{first_name} {last_name}"
print(full_name)

# creating an email based on the name
first_name_cleaned = unidecode(first_name.lower())
last_name_cleaned = unidecode(last_name.lower())
email = f"{first_name_cleaned}.{last_name_cleaned}@{fake.free_email_domain()}"
print(email)

Marie-Louise Faust
marie-louise.faust@gmail.com

In [3]:
def generate_personal_data(locale: str):
    fake = Faker(locale)

    first_name = fake.first_name()
    last_name = fake.last_name()
    full_name = f"{first_name} {last_name}"

    email_first = unidecode(first_name.lower()).replace(" ", "")
    email_last = unidecode(last_name.lower()).replace(" ", "")

    email = f"{email_first}.{email_last}@{fake.free_email_domain()}"

    address = fake.address().replace("\n", ", ")

    return full_name, email, address


locales = [
    "de_DE",
    "de_AT",
    "de_CH",
    "it_IT",
    "fr_FR",
    "en_GB",
    "da_DK",
    "es_ES",
    "nl_NL",
    "sv_SE",
    "no_NO",
]

people_data = []

for person in range(21):
    locale = random.choice(locales)
    people_data.append(generate_personal_data(locale))


df = pd.DataFrame(people_data, columns=("name", "email", "address"))

df

,name,email,address
0,Karl-August Seifert,karl-august.seifert@gmail.com,"Adelheid-Krebs-Straße 79-10, 65631 Steinfurt"
1,Else Danielsen,else.danielsen@yahoo.com,"Paulsenberget 99A, 3111 Holm"
2,Rufina Ordóñez,rufina.ordonez@yahoo.com,"Urbanización María Manuela Llano 335, Granada,..."
3,Baldassare Ferrara,baldassare.ferrara@hotmail.it,"Canale Fornaciari, 13 Appartamento 7, 00019, P..."
4,Mihaela Zingg,mihaela.zingg@yahoo.com,"Martinstrasse 51, 5010 Bülach"
5,Christian Tveit,christian.tveit@yahoo.com,"Hellandfaret 99, 1630 Ellingsen"
6,Bryan Ward,bryan.ward@yahoo.co.uk,"842 Potter Lake, West Wendy, KT0V 5BP"
7,Isak Bergström,isak.bergstrom@telia.com,"Kyrkovägen 40, 82264 Lund"
8,Olivier Thomas,olivier.thomas@hotmail.com,"Collinring 847, 6679NB, Puth"
9,Patrick Ackerl,patrick.ackerl@gmail.com,"Wenzlweg 25, 8259 Melk"
10,Anne Morris,anne.morris@outlook.com,"598 Rahman Mountains, Christianstad, KA2R 6RH"
11,Dina Lind,dina.lind@hotmail.com,"Gammel Køge Landevej 2, 3164 Løkken"
12,Johan Gashi,johan.gashi@spray.se,"Strandstigen 4, 87467 Borlänge"
13,Jonas van den Nuwenhuijzen,jonas.vandennuwenhuijzen@hotmail.com,"Esméering 2, 9959ZJ, Posterholt"
14,Calogero Iannuzzi,calogero.iannuzzi@fastwebnet.it,"Strada Iadanza, 64 Appartamento 80, 73055, Rac..."
15,Jens Blees,jens.blees@yahoo.com,"Guusdreef 037, 3139 DG, Piershil"
16,Geir Abrahamsen,geir.abrahamsen@hotmail.com,"Rønningengen 44, 4663 Johanborg"
17,Edith Brandt,edith.brandt@gmail.com,"Dunkerquegade 14, 7008 Hvalsø"
18,Serafina Luna,serafina.luna@tele2.it,"Incrocio Lanfranchi, 5, 20124, Milano (MI)"
19,Daniela Hedberg,daniela.hedberg@swipnet.se,"Skolvägen 03, 60013 Norrköping"
20,Ayse Hirt,ayse.hirt@hotmail.com,"Mayerstrasse 55, 7877 Thalwil"

In [4]:
addresses = []

for i in range(11):
    addresses.append(fake.address())

print(addresses)

['Albrechtstrasse 49\n7989 Siders', 'Hattingerstraße 855\n5741 Klagenfurt', 'Krausallee 38/37\n88282 Heinsberg', 'Kocherstr. 9/0\n8849 Gallneukirchen', 'Sylvie-Gertz-Platz 57/12\n64356 Olpe', 'Prantlgasse 9/2\n7887 Hartberg', 'Ottstrasse 50\n2859 Luzern', 'Mielcarekgasse 0\n69312 Kelheim', 'Anna-Kuhl-Gasse 37\n49658 Gelnhausen', 'Martinstrasse 55\n6372 Uster', 'Meixnerstr. 26\n3297 Hainburg an der Donau']

In [5]:
check_in = fake.date_this_year(True, True)

min_stay = check_in + timedelta(days=1)
max_stay = check_in + timedelta(days=14)

check_out = fake.date_between_dates(date_start=min_stay, date_end=max_stay)

print(check_in)
print(check_out)

2026-11-28
2026-12-10